export enum BoletoStatusEnum {
  PENDING = 'PENDING',
  REGISTERING = 'REGISTERING',
  FAILED = 'FAILED',
  OPENED = 'OPENED',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
}
